empl.info.name=shankar
empl.info.id=20
#Arrays properties
empl.info.skills[0]=java
empl.info.skills[1]=ML
empl.info.skills[2]=AI
empl.info.skills[3]=Cloud


#List Properties
empl.info.team-member[0]=shankar
empl.info.team-member[1]=Gaurav
empl.info.team-member[2]=kuldeep

#Set Properties
empl.info.phone-number[0]=9226286425
empl.info.phone-number[1]=3088439847
empl.info.phone-number[2]=3973645433

#Map Properties
empl.info.id-details.aadharNo=279137974914
empl.info.id-details.panNo=8340474
empl.info.id-details.voterId=923274

#Has-A Properties

empl.info.company.title=PW
empl.info.company.location=noida
empl.info.company.size=20



